



# POST http://localhost:3001/users/login
# Content-Type: application/application/json

# {
#    email: test23,
#    password: test23
# }


# GET   http://localhost:3001/users/profile/ 
# cookie: 

# {
# email: test:1
# password: test1
# #  }
# POST http://localhost:3001/users/signup
# Content-Type: application/application/json

# {
#     "fistName": testVSCODE2,
#     "lastName": testVSCODE2,
#     "email": testVSCODE2,
#     "password": testVSCODE2,

# }